services:
  egoric-studio:
    build:
      context: .
      dockerfile: Dockerfile
    image: egoric-studio:latest
    container_name: egoric-studio-app
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - egoric-studio-network

networks:
  egoric-studio-network:
    driver: bridge
